// Generated by `supabase gen types typescript` (mcp Supabase generate_typescript_types)
// from the connected "mlb-edge" project (ref jjrnimrljknyrvkyszih). Do not edit by
// hand — regenerate after applying a migration. Only the scientific tables and the
// pre-existing legacy tables are represented.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  public: {
    Tables: {
      circuit_breaker_events: {
        Row: {
          breaker_type: string
          decision_snapshot_id: string | null
          evidence: Json | null
          game_pk: number | null
          id: string
          market_key: string | null
          model_id: string | null
          reason: string
          recovery_condition: string | null
          resolution_note: string | null
          resolved_at: string | null
          resolved_by: string | null
          severity: string
          status: string
          triggered_at: string
        }
        Insert: {
          breaker_type: string
          decision_snapshot_id?: string | null
          evidence?: Json | null
          game_pk?: number | null
          id?: string
          market_key?: string | null
          model_id?: string | null
          reason: string
          recovery_condition?: string | null
          resolution_note?: string | null
          resolved_at?: string | null
          resolved_by?: string | null
          severity?: string
          status?: string
          triggered_at?: string
        }
        Update: {
          breaker_type?: string
          decision_snapshot_id?: string | null
          evidence?: Json | null
          game_pk?: number | null
          id?: string
          market_key?: string | null
          model_id?: string | null
          reason?: string
          recovery_condition?: string | null
          resolution_note?: string | null
          resolved_at?: string | null
          resolved_by?: string | null
          severity?: string
          status?: string
          triggered_at?: string
        }
        Relationships: []
      }
      decision_snapshots: {
        Row: {
          config_checksum: string
          content_hash: string
          decision: string
          downside_probability: number | null
          entry_id: string | null
          event_start_time: string | null
          expected_profit: number | null
          expected_return: number | null
          feature_cutoff: string
          generated_at: string
          id: string
          input_hash: string | null
          model_version: string
          payout_snapshot_id: string | null
          policy_id: string
          policy_version: string
          projection_snapshot_id: string | null
          reasons: Json
          result: Json
          scientific_facts: Json | null
          subject_key: string
          subject_type: string
          variance: number | null
          vetoes: Json
        }
        Insert: {
          config_checksum: string
          content_hash: string
          decision: string
          downside_probability?: number | null
          entry_id?: string | null
          event_start_time?: string | null
          expected_profit?: number | null
          expected_return?: number | null
          feature_cutoff: string
          generated_at?: string
          id?: string
          input_hash?: string | null
          model_version: string
          payout_snapshot_id?: string | null
          policy_id: string
          policy_version: string
          projection_snapshot_id?: string | null
          reasons?: Json
          result?: Json
          scientific_facts?: Json | null
          subject_key: string
          subject_type: string
          variance?: number | null
          vetoes?: Json
        }
        Update: {
          config_checksum?: string
          content_hash?: string
          decision?: string
          downside_probability?: number | null
          entry_id?: string | null
          event_start_time?: string | null
          expected_profit?: number | null
          expected_return?: number | null
          feature_cutoff?: string
          generated_at?: string
          id?: string
          input_hash?: string | null
          model_version?: string
          payout_snapshot_id?: string | null
          policy_id?: string
          policy_version?: string
          projection_snapshot_id?: string | null
          reasons?: Json
          result?: Json
          scientific_facts?: Json | null
          subject_key?: string
          subject_type?: string
          variance?: number | null
          vetoes?: Json
        }
        Relationships: [
          {
            foreignKeyName: "decision_snapshots_payout_snapshot_id_fkey"
            columns: ["payout_snapshot_id"]
            isOneToOne: false
            referencedRelation: "payout_snapshots"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "decision_snapshots_projection_snapshot_id_fkey"
            columns: ["projection_snapshot_id"]
            isOneToOne: false
            referencedRelation: "projection_snapshots"
            referencedColumns: ["id"]
          },
        ]
      }
      drift_reports: {
        Row: {
          breach: boolean
          computed_at: string
          current_count: number
          current_window: Json | null
          drift_level: string
          feature_name: string
          feature_type: string
          id: string
          insufficient_data: boolean
          market_key: string
          metric: string
          metric_value: number | null
          model_id: string | null
          reference_count: number
          reference_window: Json | null
          thresholds: Json | null
        }
        Insert: {
          breach?: boolean
          computed_at?: string
          current_count?: number
          current_window?: Json | null
          drift_level: string
          feature_name: string
          feature_type?: string
          id?: string
          insufficient_data?: boolean
          market_key: string
          metric?: string
          metric_value?: number | null
          model_id?: string | null
          reference_count?: number
          reference_window?: Json | null
          thresholds?: Json | null
        }
        Update: {
          breach?: boolean
          computed_at?: string
          current_count?: number
          current_window?: Json | null
          drift_level?: string
          feature_name?: string
          feature_type?: string
          id?: string
          insufficient_data?: boolean
          market_key?: string
          metric?: string
          metric_value?: number | null
          model_id?: string | null
          reference_count?: number
          reference_window?: Json | null
          thresholds?: Json | null
        }
        Relationships: [
          {
            foreignKeyName: "drift_reports_model_id_fkey"
            columns: ["model_id"]
            isOneToOne: false
            referencedRelation: "model_registry"
            referencedColumns: ["id"]
          },
        ]
      }
      feature_snapshots: {
        Row: {
          computed_at: string
          data_as_of: string
          entity_id: string
          entity_type: string
          feature_cutoff: string
          feature_version: string
          features: Json
          game_pk: number | null
          id: string
          market_key: string
          missing_features: Json
          source_hash: string
          source_observation_ids: string[]
        }
        Insert: {
          computed_at?: string
          data_as_of: string
          entity_id: string
          entity_type: string
          feature_cutoff: string
          feature_version: string
          features: Json
          game_pk?: number | null
          id?: string
          market_key: string
          missing_features?: Json
          source_hash: string
          source_observation_ids?: string[]
        }
        Update: {
          computed_at?: string
          data_as_of?: string
          entity_id?: string
          entity_type?: string
          feature_cutoff?: string
          feature_version?: string
          features?: Json
          game_pk?: number | null
          id?: string
          market_key?: string
          missing_features?: Json
          source_hash?: string
          source_observation_ids?: string[]
        }
        Relationships: []
      }
      grading_history: {
        Row: {
          actual_side: string | null
          actual_value: number | null
          decision_snapshot_id: string | null
          graded_at: string
          grading_rule_version: string
          id: string
          new_grade: string
          official_result_id: string | null
          previous_grade: string | null
          projection_snapshot_id: string | null
          reason: string | null
          selected_side: string | null
        }
        Insert: {
          actual_side?: string | null
          actual_value?: number | null
          decision_snapshot_id?: string | null
          graded_at?: string
          grading_rule_version: string
          id?: string
          new_grade: string
          official_result_id?: string | null
          previous_grade?: string | null
          projection_snapshot_id?: string | null
          reason?: string | null
          selected_side?: string | null
        }
        Update: {
          actual_side?: string | null
          actual_value?: number | null
          decision_snapshot_id?: string | null
          graded_at?: string
          grading_rule_version?: string
          id?: string
          new_grade?: string
          official_result_id?: string | null
          previous_grade?: string | null
          projection_snapshot_id?: string | null
          reason?: string | null
          selected_side?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "grading_history_decision_snapshot_id_fkey"
            columns: ["decision_snapshot_id"]
            isOneToOne: false
            referencedRelation: "decision_snapshots"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "grading_history_official_result_id_fkey"
            columns: ["official_result_id"]
            isOneToOne: false
            referencedRelation: "official_results"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "grading_history_projection_snapshot_id_fkey"
            columns: ["projection_snapshot_id"]
            isOneToOne: false
            referencedRelation: "projection_snapshots"
            referencedColumns: ["id"]
          },
        ]
      }
      market_validation_metrics: {
        Row: {
          baseline_comparison: Json | null
          brier: number | null
          calibration: Json | null
          computed_at: string
          expected_return: number | null
          id: string
          log_loss: number | null
          longest_losing_streak: number | null
          mae: number | null
          market_key: string
          max_drawdown: number | null
          model_id: string | null
          realized_return: number | null
          rmse: number | null
          sample_count: number
          scored_count: number
          segment: string | null
          window_end: string | null
          window_start: string | null
          window_type: string
        }
        Insert: {
          baseline_comparison?: Json | null
          brier?: number | null
          calibration?: Json | null
          computed_at?: string
          expected_return?: number | null
          id?: string
          log_loss?: number | null
          longest_losing_streak?: number | null
          mae?: number | null
          market_key: string
          max_drawdown?: number | null
          model_id?: string | null
          realized_return?: number | null
          rmse?: number | null
          sample_count?: number
          scored_count?: number
          segment?: string | null
          window_end?: string | null
          window_start?: string | null
          window_type: string
        }
        Update: {
          baseline_comparison?: Json | null
          brier?: number | null
          calibration?: Json | null
          computed_at?: string
          expected_return?: number | null
          id?: string
          log_loss?: number | null
          longest_losing_streak?: number | null
          mae?: number | null
          market_key?: string
          max_drawdown?: number | null
          model_id?: string | null
          realized_return?: number | null
          rmse?: number | null
          sample_count?: number
          scored_count?: number
          segment?: string | null
          window_end?: string | null
          window_start?: string | null
          window_type?: string
        }
        Relationships: [
          {
            foreignKeyName: "market_validation_metrics_model_id_fkey"
            columns: ["model_id"]
            isOneToOne: false
            referencedRelation: "model_registry"
            referencedColumns: ["id"]
          },
        ]
      }
      model_registry: {
        Row: {
          algorithm: string | null
          approved_at: string | null
          approved_by: string | null
          created_at: string
          feature_version: string
          git_commit_sha: string | null
          hyperparameters: Json | null
          id: string
          lifecycle_status: string
          market_key: string
          model_name: string
          model_version: string
          retired_at: string | null
          suspended_at: string | null
          suspended_reason: string | null
          training_data_hash: string | null
          training_period_end: string | null
          training_period_start: string | null
          training_support: Json | null
          updated_at: string
          validation_period_end: string | null
          validation_period_start: string | null
        }
        Insert: {
          algorithm?: string | null
          approved_at?: string | null
          approved_by?: string | null
          created_at?: string
          feature_version: string
          git_commit_sha?: string | null
          hyperparameters?: Json | null
          id?: string
          lifecycle_status?: string
          market_key: string
          model_name: string
          model_version: string
          retired_at?: string | null
          suspended_at?: string | null
          suspended_reason?: string | null
          training_data_hash?: string | null
          training_period_end?: string | null
          training_period_start?: string | null
          training_support?: Json | null
          updated_at?: string
          validation_period_end?: string | null
          validation_period_start?: string | null
        }
        Update: {
          algorithm?: string | null
          approved_at?: string | null
          approved_by?: string | null
          created_at?: string
          feature_version?: string
          git_commit_sha?: string | null
          hyperparameters?: Json | null
          id?: string
          lifecycle_status?: string
          market_key?: string
          model_name?: string
          model_version?: string
          retired_at?: string | null
          suspended_at?: string | null
          suspended_reason?: string | null
          training_data_hash?: string | null
          training_period_end?: string | null
          training_period_start?: string | null
          training_support?: Json | null
          updated_at?: string
          validation_period_end?: string | null
          validation_period_start?: string | null
        }
        Relationships: []
      }
      official_results: {
        Row: {
          effective_at: string
          game_pk: number
          game_status: string
          id: string
          market_key: string
          official_value: number | null
          payload_hash: string
          player_id: number | null
          raw_observation_id: string | null
          retrieved_at: string
          source: string
          source_record: string | null
          supersedes_id: string | null
          version: number
        }
        Insert: {
          effective_at: string
          game_pk: number
          game_status: string
          id?: string
          market_key: string
          official_value?: number | null
          payload_hash: string
          player_id?: number | null
          raw_observation_id?: string | null
          retrieved_at?: string
          source: string
          source_record?: string | null
          supersedes_id?: string | null
          version?: number
        }
        Update: {
          effective_at?: string
          game_pk?: number
          game_status?: string
          id?: string
          market_key?: string
          official_value?: number | null
          payload_hash?: string
          player_id?: number | null
          raw_observation_id?: string | null
          retrieved_at?: string
          source?: string
          source_record?: string | null
          supersedes_id?: string | null
          version?: number
        }
        Relationships: [
          {
            foreignKeyName: "official_results_raw_observation_id_fkey"
            columns: ["raw_observation_id"]
            isOneToOne: false
            referencedRelation: "raw_observations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "official_results_supersedes_id_fkey"
            columns: ["supersedes_id"]
            isOneToOne: false
            referencedRelation: "official_results"
            referencedColumns: ["id"]
          },
        ]
      }
      payout_snapshots: {
        Row: {
          captured_at: string
          effective_from: string | null
          effective_to: string | null
          entry_id: string | null
          format: string
          id: string
          is_verified: boolean
          payload_hash: string
          pick_count: number
          rules: Json
          source: string
          tier_composition: Json | null
          version: string
        }
        Insert: {
          captured_at?: string
          effective_from?: string | null
          effective_to?: string | null
          entry_id?: string | null
          format: string
          id?: string
          is_verified?: boolean
          payload_hash: string
          pick_count: number
          rules: Json
          source: string
          tier_composition?: Json | null
          version: string
        }
        Update: {
          captured_at?: string
          effective_from?: string | null
          effective_to?: string | null
          entry_id?: string | null
          format?: string
          id?: string
          is_verified?: boolean
          payload_hash?: string
          pick_count?: number
          rules?: Json
          source?: string
          tier_composition?: Json | null
          version?: string
        }
        Relationships: []
      }
      projection_snapshots: {
        Row: {
          confidence: number | null
          config_checksum: string
          data_as_of: string
          data_quality: number | null
          distribution_summary: Json | null
          event_start_time: string | null
          feature_cutoff: string
          feature_snapshot_id: string | null
          feature_version: string
          fragility: number | null
          game_pk: number | null
          generated_at: string
          id: string
          input_hash: string
          line: number
          line_snapshot_id: string | null
          market_key: string
          model_id: string | null
          model_version: string
          player_id: number | null
          prob_less: number | null
          prob_more: number | null
          prob_push: number | null
          volatility: number | null
        }
        Insert: {
          confidence?: number | null
          config_checksum: string
          data_as_of: string
          data_quality?: number | null
          distribution_summary?: Json | null
          event_start_time?: string | null
          feature_cutoff: string
          feature_snapshot_id?: string | null
          feature_version: string
          fragility?: number | null
          game_pk?: number | null
          generated_at?: string
          id?: string
          input_hash: string
          line: number
          line_snapshot_id?: string | null
          market_key: string
          model_id?: string | null
          model_version: string
          player_id?: number | null
          prob_less?: number | null
          prob_more?: number | null
          prob_push?: number | null
          volatility?: number | null
        }
        Update: {
          confidence?: number | null
          config_checksum?: string
          data_as_of?: string
          data_quality?: number | null
          distribution_summary?: Json | null
          event_start_time?: string | null
          feature_cutoff?: string
          feature_snapshot_id?: string | null
          feature_version?: string
          fragility?: number | null
          game_pk?: number | null
          generated_at?: string
          id?: string
          input_hash?: string
          line?: number
          line_snapshot_id?: string | null
          market_key?: string
          model_id?: string | null
          model_version?: string
          player_id?: number | null
          prob_less?: number | null
          prob_more?: number | null
          prob_push?: number | null
          volatility?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "projection_snapshots_feature_snapshot_id_fkey"
            columns: ["feature_snapshot_id"]
            isOneToOne: false
            referencedRelation: "feature_snapshots"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "projection_snapshots_line_snapshot_id_fkey"
            columns: ["line_snapshot_id"]
            isOneToOne: false
            referencedRelation: "prizepicks_line_snapshots"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "projection_snapshots_model_id_fkey"
            columns: ["model_id"]
            isOneToOne: false
            referencedRelation: "model_registry"
            referencedColumns: ["id"]
          },
        ]
      }
      prizepicks_line_snapshots: {
        Row: {
          captured_at: string
          entry_id: string
          game_number: number | null
          game_pk: number | null
          id: string
          is_verified: boolean
          line: number
          market_key: string
          payload_hash: string
          player_id: number | null
          player_name: string | null
          projection_type: string
          source_reference: string | null
          source_type: string
          supersedes_id: string | null
          user_id: string | null
          verification_status: string
        }
        Insert: {
          captured_at?: string
          entry_id: string
          game_number?: number | null
          game_pk?: number | null
          id?: string
          is_verified?: boolean
          line: number
          market_key: string
          payload_hash: string
          player_id?: number | null
          player_name?: string | null
          projection_type?: string
          source_reference?: string | null
          source_type: string
          supersedes_id?: string | null
          user_id?: string | null
          verification_status?: string
        }
        Update: {
          captured_at?: string
          entry_id?: string
          game_number?: number | null
          game_pk?: number | null
          id?: string
          is_verified?: boolean
          line?: number
          market_key?: string
          payload_hash?: string
          player_id?: number | null
          player_name?: string | null
          projection_type?: string
          source_reference?: string | null
          source_type?: string
          supersedes_id?: string | null
          user_id?: string | null
          verification_status?: string
        }
        Relationships: [
          {
            foreignKeyName: "prizepicks_line_snapshots_supersedes_id_fkey"
            columns: ["supersedes_id"]
            isOneToOne: false
            referencedRelation: "prizepicks_line_snapshots"
            referencedColumns: ["id"]
          },
        ]
      }
      raw_observations: {
        Row: {
          available_at: string
          captured_at: string
          effective_at: string
          entity_id: string
          entity_type: string
          event_time: string | null
          game_pk: number | null
          id: string
          observation_type: string
          parser_version: string
          payload: Json
          payload_hash: string
          schema_version: string
          source: string
          source_record_id: string | null
        }
        Insert: {
          available_at: string
          captured_at?: string
          effective_at: string
          entity_id: string
          entity_type: string
          event_time?: string | null
          game_pk?: number | null
          id?: string
          observation_type: string
          parser_version?: string
          payload: Json
          payload_hash: string
          schema_version?: string
          source: string
          source_record_id?: string | null
        }
        Update: {
          available_at?: string
          captured_at?: string
          effective_at?: string
          entity_id?: string
          entity_type?: string
          event_time?: string | null
          game_pk?: number | null
          id?: string
          observation_type?: string
          parser_version?: string
          payload?: Json
          payload_hash?: string
          schema_version?: string
          source?: string
          source_record_id?: string | null
        }
        Relationships: []
      }
      user_player_favorites: {
        Row: {
          created_at: string
          id: string
          player_id: number
          user_id: string
        }
        Insert: {
          created_at?: string
          id?: string
          player_id: number
          user_id?: string
        }
        Update: {
          created_at?: string
          id?: string
          player_id?: number
          user_id?: string
        }
        Relationships: []
      }
      user_player_follows: {
        Row: {
          created_at: string
          id: string
          is_active: boolean
          last_viewed_at: string | null
          notes: string | null
          player_id: number
          preferred_metrics: string[]
          updated_at: string
          user_id: string
        }
        Insert: {
          created_at?: string
          id?: string
          is_active?: boolean
          last_viewed_at?: string | null
          notes?: string | null
          player_id: number
          preferred_metrics?: string[]
          updated_at?: string
          user_id?: string
        }
        Update: {
          created_at?: string
          id?: string
          is_active?: boolean
          last_viewed_at?: string | null
          notes?: string | null
          player_id?: number
          preferred_metrics?: string[]
          updated_at?: string
          user_id?: string
        }
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DefaultSchema = Database["public"]

export type Tables<T extends keyof DefaultSchema["Tables"]> =
  DefaultSchema["Tables"][T]["Row"]
export type TablesInsert<T extends keyof DefaultSchema["Tables"]> =
  DefaultSchema["Tables"][T]["Insert"]
export type TablesUpdate<T extends keyof DefaultSchema["Tables"]> =
  DefaultSchema["Tables"][T]["Update"]
